language: go

go:
  - 1.8.x

notifications:
  email: false

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

script:
  - overalls -project=github.com/maprost/pqx -covermode=count
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN